At the top of every python file, I would put this following code here: (it connects you to our github folder)

In [1]:
!git clone https://github.com/aldenbarnes/structure_properties_fall_2026.git
%cd /content/structure_properties_fall_2026

fatal: destination path 'structure_properties_fall_2026' already exists and is not an empty directory.
/content/structure_properties_fall_2026

In [ ]:
#you can make comments with the pound key

In [2]:
#here is what the directory looks like:
!ls

Code  Data  README.md  rent_estimator.ipynb

In [3]:
#here is the code (test_colab is this script):
!ls Code

setup  test_colab.ipynb

In [4]:
#this is how to make a dataframe
import pandas as pd
df = pd.read_csv("https://data.sf.gov/api/v3/views/ramy-di5m/export.csv?accessType=DOWNLOAD")

In [5]:
# view the dataframe
df

,EAS FullID,EAS BaseID,EAS AddressID,Address Number,Address Number Suffix,Street Name,Street Type,CNN,Street Full Name,EAS SubID,...,supervisor,supdistpad,supname,nhood,complete_landmark_name,landmark_aliases,direct_source,data_as_of,data_updated_at,data_loaded_at
0,275485-814017-0,275485,814017,801,NaN,JONES,ST,7575000,JONES ST,814017,...,3,3,Danny Sauter,Nob Hill,NaN,NaN,State of CA,2026/10/02 06:00:51 PM,2019/06/12 06:45:59 PM,2026/10/03 08:08:54 PM
1,361076-577595-400608,361076,577595,3527,NaN,18TH,ST,881000,18TH ST,577595,...,9,9,Jackie Fielder,Mission,NaN,NaN,SF DBI,2026/10/02 06:00:51 PM,1970/01/01 12:00:00 AM,2026/10/03 08:08:54 PM
2,472243-702883-576706,472243,702883,841,NaN,SAN JOSE,AVE,11438102,SAN JOSE AVE,702883,...,9,9,Jackie Fielder,Bernal Heights,NaN,NaN,SF DBI,2026/10/02 06:00:51 PM,2014/09/02 09:51:46 AM,2026/10/03 08:08:54 PM
3,302098-755052-0,302098,755052,274,NaN,26TH,AVE,1470000,26TH AVE,755052,...,1,1,Connie Chan,Outer Richmond,NaN,NaN,State of CA,2026/10/02 06:00:51 PM,2019/05/23 06:48:36 PM,2026/10/03 08:08:54 PM
4,495691-762736-0,495691,762736,298,NaN,09TH,ST,453000,09TH ST,762736,...,6,6,Matt Dorsey,South of Market,NaN,NaN,State of CA,2026/10/02 06:00:51 PM,2024/12/27 09:48:44 AM,2026/10/03 08:08:54 PM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
388614,488452-735662-576661,488452,735662,1320,NaN,FITZGERALD,AVE,5601001,FITZGERALD AVE,735662,...,10,10,Shamann Walton,Bayview Hunters Point,NaN,NaN,SF DBI,2026/10/02 06:00:51 PM,2014/08/29 12:30:59 PM,2026/10/03 08:08:54 PM
388615,280153-845563-0,280153,845563,1474,NaN,SACRAMENTO,ST,11245000,SACRAMENTO ST,845563,...,3,3,Danny Sauter,Nob Hill,NaN,NaN,State of CA,2026/10/02 06:00:51 PM,2019/06/13 07:00:11 PM,2026/10/03 08:08:54 PM
388616,280699-489059-309981,280699,489059,1000,NaN,PINE,ST,10471000,PINE ST,489059,...,3,3,Danny Sauter,Nob Hill,NaN,NaN,SF DBI,2026/10/02 06:00:51 PM,1970/01/01 12:00:00 AM,2026/10/03 08:08:54 PM
388617,281038-819145-0,281038,819145,805,NaN,LEAVENWORTH,ST,8246000,LEAVENWORTH ST,819145,...,3,3,Danny Sauter,Nob Hill,NaN,NaN,State of CA,2026/10/02 06:00:51 PM,2024/10/04 01:28:51 AM,2026/10/03 08:08:54 PM
388618,418390-636803-460040,418390,636803,16,NaN,LAGUNITAS,DR,7999000,LAGUNITAS DR,636803,...,7,7,Myrna Melgar,West of Twin Peaks,NaN,NaN,SF DBI,2026/10/02 06:00:51 PM,1970/01/01 12:00:00 AM,2026/10/03 08:08:54 PM

In [6]:
# view the columns
print(df.columns)

Index(['EAS FullID', 'EAS BaseID', 'EAS AddressID', 'Address Number',
       'Address Number Suffix', 'Street Name', 'Street Type', 'CNN',
       'Street Full Name', 'EAS SubID', 'Unit Number', 'Parcel Number',
       'Block', 'Lot', 'ZIP Code', 'Address', 'Longitude', 'Latitude', 'point',
       'supdist', 'numbertext', 'supervisor', 'supdistpad', 'supname', 'nhood',
       'complete_landmark_name', 'landmark_aliases', 'direct_source',
       'data_as_of', 'data_updated_at', 'data_loaded_at'],
      dtype='object')

In [7]:
# lets save the useful columns
df_useful = df[['EAS FullID', 'Address', 'Longitude', 'Latitude', 'nhood']]
df_useful.head() # .head gives the first few rows

,EAS FullID,Address,Longitude,Latitude,nhood
0,275485-814017-0,801 JONES ST #312,-122.413718,37.788813,Nob Hill
1,361076-577595-400608,3527 18TH ST,-122.422239,37.761477,Mission
2,472243-702883-576706,841 SAN JOSE AVE,-122.423347,37.741567,Bernal Heights
3,302098-755052-0,274 26TH AVE #201,-122.485798,37.784365,Outer Richmond
4,495691-762736-0,298 09TH ST,-122.411964,37.773855,South of Market

In [8]:
df_useful.to_csv("Data/address_geography_nhood_ID.csv", index=False)

In [9]:
!git config --global user.name "aldenbarnes"
!git config --global user.email "aldenspencerbarnes@gmail.com"

In [10]:
!git add Data/address_geography_nhood_ID.csv
!git commit -m "Add address geography neighborhood ID data"

[main ccfa0a7] Add address geography neighborhood ID data
 1 file changed, 388620 insertions(+)
 create mode 100644 Data/address_geography_nhood_ID.csv

In [11]:
import getpass

token = getpass.getpass("GitHub token: ")

print("Token received:", len(token), "characters")

GitHub token: ··········
Token received: 93 characters

In [12]:
import subprocess

url = f"https://aldenbarnes:{token}@github.com/aldenbarnes/structure_properties_fall_2026.git"

result = subprocess.run(
    ["git", "push", url, "main"],
    capture_output=True,
    text=True
)

print(result.stdout)
print(result.stderr)

To https://github.com/aldenbarnes/structure_properties_fall_2026.git
   6f38eb0..ccfa0a7  main -> main