At the top of every python file, I would put this following code here: (it connects you to our github folder)

In [53]:
!git clone https://github.com/aldenbarnes/structure_properties_fall_2026.git

Cloning into 'structure_properties_fall_2026'...
remote: Enumerating objects: 62, done.
remote: Counting objects: 100% (62/62), done.
remote: Compressing objects: 100% (58/58), done.
remote: Total 62 (delta 26), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (62/62), 29.50 KiB | 4.21 MiB/s, done.
Resolving deltas: 100% (26/26), done.

In [54]:
#you can make comments with the pound key

In [55]:
#here is what the directory looks like:
!ls

Code  README.md		    structure_properties_fall_2026
Data  rent_estimator.ipynb  Untitled1.ipynb

In [56]:
#here is the code (test_colab is this script):
!ls Code

setup  test_colab.ipynb

In [57]:
#this is how to make a dataframe
import pandas as pd
df = pd.read_csv("https://data.sf.gov/api/v3/views/ramy-di5m/export.csv?accessType=DOWNLOAD")

In [58]:
# view the dataframe
df

,EAS FullID,EAS BaseID,EAS AddressID,Address Number,Address Number Suffix,Street Name,Street Type,CNN,Street Full Name,EAS SubID,...,supervisor,supdistpad,supname,nhood,complete_landmark_name,landmark_aliases,direct_source,data_as_of,data_updated_at,data_loaded_at
0,314359-759312-0,314359,759312,1224,NaN,45TH,AVE,1998000,45TH AVE,759312,...,4,4,Alan Wong,Sunset/Parkside,NaN,NaN,State of CA,2026/10/02 06:00:51 PM,2019/05/28 06:54:01 PM,2026/10/03 08:08:54 PM
1,476675-710227-0,476675,710227,549,NaN,NOE,ST,9615000,NOE ST,710227,...,8,8,Rafael Mandelman,Castro/Upper Market,NaN,NaN,SF DBI,2026/10/02 06:00:51 PM,2025/06/03 09:55:25 AM,2026/10/03 08:08:54 PM
2,402695-755503-0,402695,755503,3225,NaN,26TH,ST,1519000,26TH ST,755503,...,9,9,Jackie Fielder,Mission,NaN,NaN,State of CA,2026/10/02 06:00:51 PM,2019/05/23 06:48:36 PM,2026/10/03 08:08:54 PM
3,275907-481256-491429,275907,481256,2655,NaN,HYDE,ST,7150000,HYDE ST,481256,...,2,2,Stephen Sherrill,Russian Hill,NaN,NaN,SF DBI,2026/10/02 06:00:51 PM,2019/03/12 08:49:00 AM,2026/10/03 08:08:54 PM
4,281827-809372-0,281827,809372,360,NaN,HYDE,ST,7117000,HYDE ST,809372,...,5,5,Bilal Mahmood,Tenderloin,NaN,NaN,State of CA,2026/10/02 06:00:51 PM,2019/06/11 07:05:22 PM,2026/10/03 08:08:54 PM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
388614,488452-735662-576661,488452,735662,1320,NaN,FITZGERALD,AVE,5601001,FITZGERALD AVE,735662,...,10,10,Shamann Walton,Bayview Hunters Point,NaN,NaN,SF DBI,2026/10/02 06:00:51 PM,2014/08/29 12:30:59 PM,2026/10/03 08:08:54 PM
388615,280153-845563-0,280153,845563,1474,NaN,SACRAMENTO,ST,11245000,SACRAMENTO ST,845563,...,3,3,Danny Sauter,Nob Hill,NaN,NaN,State of CA,2026/10/02 06:00:51 PM,2019/06/13 07:00:11 PM,2026/10/03 08:08:54 PM
388616,280699-489059-309981,280699,489059,1000,NaN,PINE,ST,10471000,PINE ST,489059,...,3,3,Danny Sauter,Nob Hill,NaN,NaN,SF DBI,2026/10/02 06:00:51 PM,1970/01/01 12:00:00 AM,2026/10/03 08:08:54 PM
388617,281038-819145-0,281038,819145,805,NaN,LEAVENWORTH,ST,8246000,LEAVENWORTH ST,819145,...,3,3,Danny Sauter,Nob Hill,NaN,NaN,State of CA,2026/10/02 06:00:51 PM,2024/10/04 01:28:51 AM,2026/10/03 08:08:54 PM
388618,418390-636803-460040,418390,636803,16,NaN,LAGUNITAS,DR,7999000,LAGUNITAS DR,636803,...,7,7,Myrna Melgar,West of Twin Peaks,NaN,NaN,SF DBI,2026/10/02 06:00:51 PM,1970/01/01 12:00:00 AM,2026/10/03 08:08:54 PM

In [59]:
# view the columns
print(df.columns)

Index(['EAS FullID', 'EAS BaseID', 'EAS AddressID', 'Address Number',
       'Address Number Suffix', 'Street Name', 'Street Type', 'CNN',
       'Street Full Name', 'EAS SubID', 'Unit Number', 'Parcel Number',
       'Block', 'Lot', 'ZIP Code', 'Address', 'Longitude', 'Latitude', 'point',
       'supdist', 'numbertext', 'supervisor', 'supdistpad', 'supname', 'nhood',
       'complete_landmark_name', 'landmark_aliases', 'direct_source',
       'data_as_of', 'data_updated_at', 'data_loaded_at'],
      dtype='object')

In [60]:
# lets save the useful columns
df_useful = df[['EAS FullID', 'Address', 'Longitude', 'Latitude', 'nhood']]
df_useful.head() # .head gives the first few rows

,EAS FullID,Address,Longitude,Latitude,nhood
0,314359-759312-0,1224 45TH AVE #2,-122.504755,37.763709,Sunset/Parkside
1,476675-710227-0,549 NOE ST,-122.432567,37.760356,Castro/Upper Market
2,402695-755503-0,3225 26TH ST #17,-122.414241,37.749108,Mission
3,275907-481256-491429,2655 HYDE ST,-122.420596,37.805474,Russian Hill
4,281827-809372-0,360 HYDE ST #406,-122.415813,37.784265,Tenderloin

In [61]:
!git config --global user.name "aldenbarnes"
!git config --global user.email "aldenspencerbarnes@gmail.com"

In [62]:
!git add Data/address_geography_nhood_ID.csv
!git commit -m "Add address geography neighborhood ID data"

On branch main
Your branch is ahead of 'origin/main' by 1 commit.
  (use "git push" to publish your local commits)

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	structure_properties_fall_2026/

nothing added to commit but untracked files present (use "git add" to track)

In [69]:
import getpass

token = getpass.getpass("GitHub token: ")

print("Token received:", len(token), "characters")

GitHub token: ··········
Token received: 93 characters

In [70]:
import subprocess

url = f"https://aldenbarnes:{token}@github.com/aldenbarnes/structure_properties_fall_2026.git"

result = subprocess.run(
    ["git", "push", url, "main"],
    capture_output=True,
    text=True
)

print(result.stdout)
print(result.stderr)

To https://github.com/aldenbarnes/structure_properties_fall_2026.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/aldenbarnes/structure_properties_fall_2026.git'
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.